### ISSUE TITLE
I feel like I've seen this before...

### ISSUE THREAD

**Issue by OneCricketeer** [sternetj/PandoraNotifier#1]
[Pandora Enhancer](https://chrome.google.com/webstore/detail/pandora-enhancer/cfkpeohmdjckkiblfeplofpibkcajfbo) - I see you left a review on this one :smile: It says it refreshes the page when it detects the music is not being played, which very well may be when ads are being loaded. 

[RadioEnhancer](https://chrome.google.com/webstore/detail/radioenhancer/lfijnebfkjdclmcedinoknekamigckii) - Used to work, no longer being maintained, BUT there is [source code](https://github.com/cbcoding/RadioEnhancer)

**Comment by sternetj** [comment]
This extension no longer uses notifications and is now a mini-player for Pandora.
